language: c++
os:
- osx
env:
  matrix:
  - SBAVER=1.0.26
  global:
  - secure: DFXnBxK+BAZjYObnuEFU3widEzzZLgroYsjbGm0OVUqsWwmFBOOiN/99VdnEfdK9zgK8NR9Uj5/91S8zVtpSKouhBczQGAin8fxCAtgqNqZc/n81Bq/NNzMI6ecU+FwVicSf7BEFHnuvGi1ZSuFLIMj71sdcUxdisvfqoXIxi+oclPUOx5cPc3WkOPrDR82Et9b3KfujAAe/10GwyLP6fvwQ5F+36A+ukE7WHOL+9lJ0GVUgbUwEy77xWmKQCNDTCYT3tNnA8mVC906+MXZZIwndSo6Qy9Ti+TTC2gGNdM0rJd117Woq9OdQnHPPfngpiTuudtjkJHxtOZw9cEzdf33jDpNerLrxh9LXOOxTaSD26S6j+/aTdsReEjB/OFJNo/PRqRrim8O7cZznxdbsnFH7PADCsU6ygvDbgedIPtUOQ5uE4saRzVVhSvV22s9Tn/7S4lZ3ORI5V1Q2uYf7W4CILMRK49mcgrJy4kr6wfWB1RNdUMHLk3bhhZOrCSUKT+lXoJRzuEsf/MiQWBkNkHJIjK33Zuk6IYebBb95PLSqgxp7VUOcQEYnaS9I0Rw3t0gspqVN0CIN1pGRMvsEp1M39uZ0S4AO2JY3jwlOudVX3brXCh41C0uXpfHKp0Hk2AaGbsZJSat6UWpIZ/0syZcKg05Dh18qo/QAKcrz/kY=
  - secure: n58kmUjwTc8X+f8Up5yJaCJl3ZWidNlehlb4IAU9g5f0p1WhWmSzQ7tlBclZjU5wwdz6NOor9yw4mN6836gHrAIK97k4oyAh1rNZr4nMHDexy/mCrhfNRwbRh5IhiZIHImaBny1VYMgv8H9oXxJ65iz0ZnAZHzF4VLKLwMSt7AuAsEjGOkaB6zPIq76SG9MxhbDhxDOgROJsgLXer5HCXXBpQ549xuuzV3YyCVEC53seZiwmM/5k81qfTHiKoVYxT9exidBQmnVBOHVBMFjmkS7rdJ4Yp2ITlPWCqrKDNnnyh6KIn20zA8ctnTo7H/bjsWlCsFs4Eztjche8BcTIf6J3qup2lf0u2qbin8ZeHC14Oe+cV0X3dfUIft7erdm2rYyxaZw+DTlJOX4j6u10kKlY8h+U3Xc/yhP3BubAN/VHpjBJG9MjvgARd68CURd0lT+kGsdvDSVG3t8kSJW1o1TQ4SkWs2xMizVB9kx3Lhvkx0V6gdsklIs2YVtN5sZyAH3U6Jg2c1lpPhgceo8k69kp8TlRksaVxTuxH2ZqGr+QfBNzetg3R5vu+StrkGgxnQM1l21hvGendyvmhTyj/L/hkQX9kzuP6zF9QA4/FfT5JP8/78vBXrAnh84cBeHj3unKEWU6DMfXTtS7YC+rAPgVgtPFm8o9Gd+0usZJO/A=
  - secure: V6wm+pZENclhCK4r1v8+Io0yRmkd9o1euyHG5XCjF0XuBomH6cKuE3uk3Ns9NBhE/gsF4umt5SRXp4vsMIE2sg8iTmqgLBv52zQH7bhCMaNhE+3iNaiVA2/s4QdwzXpZpDKmcW29qpaKuAEcjAQzEz5+ik1k00vtUgtoHOaXgQYUnLEg4IRUmonaxVRsSP0smAHHcA/Y+Q0SnDI+7GLVYDRsK/E/dQk3L0bhSyJ+f3I7fe3VCuqaZFOtW2x24cqahbLCEXwDWtw/bV/eHJes5N3RPEKImnxJ++kxX8C8htoTOzzC7jcmuG7I4BIowpZUUP3WYu3624j8v6vdp/IYbLsPu/ADHBWxxcmxLxVd7kKax4AuZWGsC6EO5dMHBPrp+yg/7qxbi72lhl6fRcdKi5jjmaB/3MwDq9vZmny7OR89BiIbJQz/l+d2XNlJ/t0jfCIudssWlevMaWngslyY7YW6rcVh+Y/tOqXOa84j1fnSiWbipfAu+nTJIGweqvzf5VeE4mrW1LWOCXZzbcWAuLpB2Q6lTYhQd5gUdST61sJv9N78mHIRcSOTJL0qmK9qL5QtG95LKtC8OAaQR5dFHJJCRMK/cmDJw3xA7Pa31DhFgU/hD4ExuQt175IU8Z6KfVzLHZvGaAhAU5KH6g5icOfNRL32Bs4n2JxwFuQPiaM=
before_install:
- source travis/before_install.sh
install:
- "./travis/install.sh"
script:
- "./travis/build.sh"
deploy:
  provider: gcs
  access_key_id: GOOGCQNIBMNORKT3EC2Y
  secret_access_key:
    secure: Q5hqPXfComQ5jnItPNsxlgyspqf04AnFd1mE4pDoUB/qQMRQ1F9EqZCo/o9bT3tNrlCRbakmD9UuULHOkFIXSRaUIZ8fFT4TbswqHGpw+EI1BrlHr+RGdAdvZClTAdHKgRgXAQBUav2aQvl0zIzvTJbenghIpt7iKgEpjxZhP6Fde5oXhYEsC8dRGW4kbCOf8q+jiuJxf0Fw0ILOL6rMXxifr5QrDkTdM4kbxFajRrT+0q6co159W039SA3X5HUtOS5VLjiNsJKoKHj+2W0jwrnpgErNSPFXwgS4c44L0w90Poq+8AtMteJW7ySNHHZbY51VfaQkTDyCDuJqlL0Gx9RAJ/9kj2SCT0clFdimBCpaCzh2WlXAWyrnidCGWKaD2HFwwV2XrrBMNj9vlOY5az5249wzUn6/ofQXsccGHy4AVaU4sriQd8jvVRCe0mhyrTJBgrBYHsyaOyWRf+PzA8jtrWkml8mXB0BVFiCOSOQEc5g2z9anAmm7gs2elpSN4dieoh77U4wY8I/Tz7NJIiDMyor+XzBtDW62xywHd8Np6qQOHbVgxivORclO6wFC35jZCTkOMtiE6IBGuqF+08lST4SemDKyy6ul25eTBm5wRZflFJUj4vXLQrKd/UaUUZ/hglQgMO/O5iHmRbSnHAs4I50y0wFLFr/hK5ixUYI=
  bucket: openkj-songbook-agent
  local-dir: deploy
  skip-cleanup: true
  on:
    branch: 
     - release
     - master
