# This is a basic workflow to help you get started with Actions

name: MacOS Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
       path: ../Qt
       key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
       cached: ${{ steps.cache-qt.outputs.cache-hit }}


    # Runs a single command using the runners shell
    - name: Run qmake
      run: qmake

    - name: Make
      run: make
    
    - name: Rename app
      run: mv SongbookAgent.app "Songbook Agent.app"
    
    - name: Run macdeployqt
      run: macdeployqt -appstore-compliant "Songbook Agent.app"

# Runs a set of commands using the runners shell
#    - name: Remove non-appstore compliant plugins
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.
